selfcustody/krux

MaixPy/components/micropython/port/include/mpconfigport.h

this change allows usage of `import io` instead of `import uio`

add weak link to uio

---

Dockerfile
Vagrantfile

Updates the Dockerfile to build the kendryte toolchain from source and updates Kboot's `BUILD.sh` script to use this same built toolchain

Build the kendryte toolchain from source

---

firmware/MaixPy/components/micropython/port/include/mpconfigport.h

logging.py uses sys.exc_info() in exception handling, for that MICROPY_PY_SYS_EXC_INFO needs to be enabled on micropython port, otherwise system may crash.

Add SYS_EXC_INFO for micropython to handle exceptions

---

i18n/translations/de-DE.json
i18n/translations/en-US.json
i18n/translations/es-MX.json
i18n/translations/fr-FR.json
i18n/translations/vi-VN.json
src/krux/key.py
src/krux/pages/home.py
src/krux/wallet.py
tests/pages/test_home.py
tests/test_key.py

Resolves #87 
- The `Public Key (xpub)` screen now shows:
1. The key origin information (fingerprint + derivation) followed by the xpub, collectively referred to as the "key expression"
2. The QR code of the key expression
3. Same as the first screen, except the xpub has been converted to a zpub for wallets that can't parse a full key expression
4. The QR code of the key expression

Separate xpub text from QR and simplify key expression logic

---

src/krux/pages/login.py

Fixes a bug where you can enter invalid numbers like "45" as a valid roll because `"45" in D6_STATES == True` 🤦

Use a list to store D6 roll states

---

src/krux/firmware.py

Buttons were disabled at boot as it starts in "touch mode" so `ENTER` press will return `None` at first time

Bug fix - Amigo wouldn't update with SDcard

---

src/krux/settings.py
tests/pages/test_login.py

Micropython behaves differently than Python 3 in quirky ways. In this case, you can't call `__dict__` on a class/type object, only on an instance object. Thus, the tests passed and the simulator worked fine, but an error occurred when testing on a real device.
This PR fixes that regression to instead call the global `dir` function on the class/type object which micropython does support.

Fix settings regression

---

src/krux/display.py
src/krux/krux_settings.py
src/krux/pages/__init__.py
src/krux/pages/home.py
src/krux/pages/login.py
src/krux/printers/thermal.py

I've made some changes to improve thermal printing speed and reliability.
Most of Krux users from Telegram group who have thermal printers and I have gojprt qr203 model. The code works fine with it. One has gojprt qr204 model, which seems to have an issue with buffer (lost bytes), so I added the `scale` and `line delay`(speed) that help solve the issue. No one there has the Adafruit printer, so @jreesun could you test the thermal prints on it?
Other finding: Reducing scale can make blacks darker, I believe some printers/power supplies may have power limitations.
As all Krux users printers use 11 `heat dots`, I removed this config so all others fit in one screen in Amigo.

Thermal print scale and speed settings

---

tests/pages/test_home.py
tests/test_context.py

I'm just taking baby-steps with some 'harmless' (I hope) tests changes, but mostly so that I can have feedback where I've missed the more correct solution.
* 1st commit feels safe, print_standard_qr() is now in utils.Utils.
* 2nd commit, not sure if it's a solution, or if it's disguising an error, because I'm not able to locate which "wait_for_something" prompt was added that makes an extra `<enter>` necessary.
* 3rd commit feels safe, screensaver waits for button instead of press, however I also altered the setting of "logo" variable because I assume that the [1:-1] slice notation was meant to strip the '\n' chars that are first and last, instead of only stripping one last space among others that would not be stripped.  I also considered expressing it like "logo string".split('\n')[1:-1] …

Changes atop commit 0752bcf intended so that tests pass

---

src/krux/pages/encryption_ui.py
src/krux/pages/login.py
tests/pages/test_encryption_ui.py
tests/test_encryption.py

* Encryption load error now shows only one error message
* Test case for encryption + decription in sequence

Encryption load error now shows only one error message

---

src/krux/camera.py
src/krux/pages/addresses.py
src/krux/qr.py
tests/shared_mocks.py
tests/test_qr.py

Doing code review and tests on the new branch `qr_code_frame_calc`

qr_code_frame_calc branch: code review + tests

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/enhancement.md
.github/ISSUE_TEMPLATE/help_wanted.md
.github/PULL_REQUEST_TEMPLATE.md

Added some templates for adding new tagged issues and PRs. Useful for:
- When a developer or krux user click to create a new issue, it will open a new page with a stylished issue with automatic tags like `bug`, `enhancement` or `help_wanted` (see [this example](https://github.com/selfcustody/krux-file-signer/issues/new/choose))
- When a developer create a new PR, it will open an already created text with selectors (about which change he/she made) and a `Description` space to talk about it.

Ci issues and pr templates

---

src/krux/pages/settings_page.py
src/krux/settings.py
tests/test_settings.py

Somewhat minor change to reduce how many writes of "settings.json" are made to flash/sd.
Defaults will be included because they are built-out as they are accessed. As the user navigates deeper into settings-namespaces, more defaults will be built out, so settings will be written more often than necessary.
* krux.pages.settings_page accesses singleton "store" instead of class "Store"
* krux.pages.settings_page explicitely calls store.save_settings() when exiting
* krux.settings.Store adds attribute ".dirty" boolean to track settings changes
* krux.settings.Store adds method ".update_file_location()" to delete old file
* krux.settings.Store.save_settings() method writes only if ".dirty" and file would be altered
* adds new tests and adjusts existing tests.

Less frequent writes of settings.json to sd/flash

---

firmware/scripts/rgbconv.py

An alternative utility script to krux_colors.py, for review by others...
potentially to replace krux_colors.py because it converts both ways, and because I believe there is a green error in krux_colors.py (however if I'm correct and krux_colors.py is adjusted to solve green, rgbconv.py would still require an option to swap byte-order).
I have a gist with further thoughts: [here](https://gist.github.com/jdlcdl/b9f476be4f5e1540ae403eb7e8310b1e)
- [* ] Bug fix
- [* ] New Feature

an alternative to krux_colors.py

---

src/krux/encryption.py

Related to issue #299
On an sdcard's FAT filesystem, when a file grows into additional sectors and is later trimmed, bytes will remain abandoned in previously used sectors.  For `seeds.json`, which holds encrypted mnemonics, this is less than ideal because it could result in ciphertext with weak encryption keys remaining on the sdcard media yet hidden from plain sight for the user.
This pr alters krux.encryption.MnemonicStorage's `.store_encrypted()` and `.del_mnemonic` methods so that `seeds.json` gets padded with spaces -- to its original size.  That is, it will never be trimmed.  Care elsewhere should be taken so that `os.remove()` is not used for `seeds.json`, as it abandons all bytes.
CAUTION: This pr may create a false-sense-of-security in the event that it fails to work, and it …

seeds.json on sdcard padded to avoid abandoned bytes

---

Dockerfile
krux

When git is installed on Windows it uses as default CRFL (\r\n) line endings, and this break the build process. This commit fixes that
More info: https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings

Fix build error when files with Windows line ending CRLF (\r\n)

---

src/krux/key.py
src/krux/pages/home_pages/home.py
src/krux/pages/login.py
src/krux/pages/wallet_settings.py

Only one ux change when customizing wallet:
* "Account Number" becomes "Account Index" (since the count starts at 0)
Many lines of code changes (no functional change) to clarify and/or simplify:
* `account_number` names simplified to `account` mostly for local variable names when not confusing.
* `account_number` changed to `account_index` where it needed to be explicit, because `account` is already an embit key.
Just a picky edit towards naming conventions: so that 
* "number" specifies counting from 1 while a behind-the-scenes "number-1" is likely taking place, and 
* "index" specifies counting from 0, just like at the end of the derivation path.
Note: existing naming conventions already use "_number" for ints that start at 1 and "_index" for those that start at 0 (except for cnc code …

Wallet customization: Account "Number" becomes "Index"

---

src/krux/psbt.py

DRAFT:  Adjustments for taproot:
* support for taproot in PSBTSigner.path_mismatch() to catch krux's wallet on wrong purpose/network/account
(derivations are a different structure and a different key for p2tr)

Adjustments for taproot, one commit at a time, little by little

---

.gitignore
Dockerfile
README.md

I had updated my Docker to the latest version (`Docker version 26.1.2, build 211e74b`) and my cache gone. I was having lots of issues with github on the clone step of the build process of the Dockerfile, now is permanently fixed!
This latest version of Docker resolved some issues with cache too, now the build process is lightning fast if you do a release for multiple devices for example.
To update your docker on Linux or WSL type `sudo apt-get update && sudo apt-get upgrade`, then to be sure, close WSL wait 2 to 3 minutes and open it again (this will force a complete restart of the WSL)

Fix dockerfile build process

---

docs/getting-started/settings.en.md

Docs: Added info about the possibility to swipe up 👍  or down 👎 in settings page

Docs: swipe up and down info to settings page

---

src/krux/pages/settings_page.py

Fix rare overflow of labels in numeral_settings. Ex.: pt-BR "Tempo para protetor de tela"

Avoid label overflow in numeral_settings

---

src/krux/pages/file_manager.py

Working in another branch where I had added many files to the sdcard, I noticed that directory listings were not sorted.  This commit sorts directory listings (naive sort) for the file manager only.

sorted directory listings in filemanager

---

src/krux/pages/home_pages/wallet_descriptor.py
src/krux/wallet.py

Related to pr #388 and suggestions from Tadeu:
`wallet.persisted` is being used as a boolean but was initialized to None.  This pr corrects treatment of `.persisted` as a boolean, initializing it to False until krux knows that the descriptor is truly persisted.

.persisted as boolean: initialized False (instead of None)

---

README.md
src/krux/pages/file_manager.py

- SD file listing now shows sorted folders first than files for better navigability
- Sorting ignores case (like when sorting a folder in Windows)

Show sorted directories first in SD filemanager

---

docs/getting-started/features/QR-transcript-tools.en.md
docs/getting-started/features/entropy.en.md
docs/getting-started/features/printing.en.md
docs/getting-started/features/tools.en.md
docs/getting-started/installing/from-pre-built-release.en.md
docs/getting-started/installing/from-source.en.md
docs/getting-started/installing/from-test-release.en.md
docs/getting-started/settings.en.md
docs/getting-started/usage/generating-a-mnemonic.en.md
docs/getting-started/usage/loading-a-mnemonic.en.md
docs/getting-started/usage/navigating-the-main-menu.en.md
docs/snippets/amigo-more-info-faq.en.txt

These are just my thoughts on improvements to documentation, however when considering to merge these, please feel free to add commits, backing-out any of these changes, else ask me and I will adjust via more commits.
~~STILL TODO:~~
* ~~many pages expect an anchor to explain adjusting the amigo screen be explained at /krux/faq/#troubleshooting-lcd-settings-on-maix-amigo however this section does not exist in the faq, this needs to be written or perhaps it already exists elsewhere?~~
* ~~/krux/getting-started/installing/from-test-release/ needs a section for manual install via ktool for the maixpy_cube~~  Since I don't have a "cube", can someone please verify?
* ~~I noticed links to seedsigner.com and bitcoiner.guide at the bottom of krux/getting-started/usage/generating-a-mnemonic but I …

release-24.07.0 docs changes only

---

src/krux/pages/__init__.py
src/krux/pages/file_manager.py
src/krux/pages/home_pages/addresses.py
src/krux/pages/home_pages/home.py
src/krux/pages/home_pages/mnemonic_backup.py
src/krux/pages/home_pages/pub_key_view.py
src/krux/pages/home_pages/sign_message_ui.py
src/krux/pages/login.py
src/krux/pages/qr_view.py
src/krux/pages/settings_page.py
src/krux/pages/tools.py
src/krux/pages/wallet_settings.py

Perhaps with another "arrow" glyph, this will look nicer, but "< Back" is still very identifiable as a special menu item.
Also changed some tuples' 2nd item to the more standard "lambda: MENU_EXIT" instead of "lambda: None"

Adds "< " to "Back" menu items

---

docs/snippets/sd-card-info-faq.en.txt
docs/troubleshooting.en.md

Returning missing link for info about microSD card

Docs: returning missing link for info about microSD card

---

tests/pages/home_pages/test_sign_message_ui.py

Prior to commit 3eba4e4 and related to signing messages, if a message contained a ":" colon character, it was converted to a " " space character.  This pr adjusts the existing unit-test so that it would fail with prior versions and succeeds with 3eba4e4's fix.
User's who need to sign on a message using a previous release of krux might note the conversion of ":" to " ", which is visible in-device while signing. (ie: In Sparrow's "Sign/Verify Message" screen, they'd convert any ":" characters in the "message" text-area to " "... and then the krux signature would verify as valid)

adjusted test to cover bugfix in commit 3eba4e4

---

firmware/font/kffview.py

Just before editing font.c's `unicode` variable, devs have likely converted a bdf to kff with a particular height-in-pixels.
kffview.py can show them, in unicode-ish ascii art, what the font will look like from the command line.
For example, if a 14 pixel-high korean font file existed as "/tmp/korean-14.kff":
```
$ python kffview.py /tmp/korean-14.kff 14 를
/tmp/korean-14.kff contains 300 glyphs:
"를" is unicode: U+B97C, decimal: 47484
░░░░░░██████████████████████░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░██░░░░
░░░░░░████████████████████░░░░░░
░░░░░░██░░░░░░░░░░░░░░░░░░░░░░░░
░░░░░░░░████████████████████░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
░░██████████████████████████████
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
░░░░░░██████████████████████░░░░ …
```

krux-font-format viewer: to inspect prior to editing font.c

---

src/krux/pages/__init__.py

The idea here was twofold:
* easier free RAM numbers to read (between 1 and 1023) usually 3 digits of precision with K or M to see the big picture,
* remember amount of free RAM before gc.collect() frees it so that we can see how much was recently collected... but this will not always be true if there is a habit of using gc.collect() within routines that are memory-costly.
Since there will be loops that absolutely require gc.collect(), perhaps we can make a habit of doing it like:
```python
pre_collect = gc.mem_free()
gc.collect()
print("%s has collected %d bytes" % (__name__, gc.mem_free() - pre_collect))
```
...so that we can at least see how much memory had been used and that gc.collect() freed it for x times for this routine?  Otherwise, a bad habit of collecting memory even when it's …

draw_ram_indicator() easier numbers to read, includes RAM just collected

---

docs/getting-started/installing/from-gui/windows.en.md

A user on KruxBR found an issue on integrity verification step on Windows, more specifically, in powershell's `Get-FileHash` and `Get-Content` commands. 
Since the `Get-FileHash` output a hash in upper case,when comparing with the output of `Get-Content` in lower case, the verification will result in a `False` value. 
But this is a Negative False. 
To fix this, we expanded the power shell command as well adding steps for a scrutiny procedure.

fixed verifying command in docs steps on windows

---

src/krux/pages/file_manager.py
tests/pages/test_file_manager.py
tests/pages/test_utils.py

- select_file_handler arg simplified to handle only files NOT dir

Simplified select_file_handler responsibilities in FileManager.select_file()

---

src/krux/pages/login.py

When `Hide mnemonic` setting is True, it will hide the mnemonic while login

Hide mnemonic when wallet loading if the Hide mnemonic setting is True

---

docs/getting-started/features/tamper-detection.en.md
docs/getting-started/features/tools.en.md

- Added links and changed text a little to better understand Tamper detection feature

Tamper detection docs changes

---

src/krux/pages/encryption_ui.py
tests/pages/test_encryption_ui.py

Fix encrypted store mnemonic error msg color

Correct color for encrypted store msg when error occur

---

src/krux/pages/keypads.py

This is a fix for one of my main frustrations when entering my passphrase - the moving "ABC" key!
As I looped through the keypads, the ABC key changed position on the numeric keypad and made me hit the delete key, meaning I had to loop through even more!
I have fixed this issue by changing the order of the keys so that the ABC key is in the bottom right of the screen for all keypad types in screens that use it.

Keeps the ABC key in the same position for all keypad types

---

src/krux/pages/__init__.py
src/krux/pages/settings_page.py
src/krux/pages/tc_code_verification.py
tests/pages/test_tc_code_verification.py

As multiple keyboards are now fixed in size it doesn't make sense to separate numbers from special chars for TC code anymore

Removed the unnecessary NUM_SPECIAL_3 

---

src/krux/pages/login.py
tests/pages/test_login.py

Fix errors when `Loading Mnemonic > Via Manual Input > Word Numbers` and input is empty and user click on "GO" btn:
- ValueError: invalid literal for int() with base 10: ''
- ValueError: invalid literal for int() with base 16: ''
- ValueError: invalid literal for int() with base 8: ''

Fix rare error when loading mnemonic word numbers

---

src/krux/pages/__init__.py
src/krux/pages/keypads.py
src/krux/touch.py
tests/pages/test_page.py
tests/test_touch.py

- Using touch only, when on any keypad and hit "ESC" then "No", then the keypad would stuck responding only index 0,0 everytime, regardless of the place touched

Fixed keypad touch index stuck after "ESC" > "No"

---

src/krux/key.py
src/krux/pages/wallet_settings.py

A minor issue found prior to release:
* If Key.policy is Miniscript, then custom_derivation was true, so it became sticky when customizing:
* became problematic if customizing for network between main/test w/o altering Policy... would not update derivation.
This pr changes key:
* no notion of "custom_derivation", derivation is like other customizable attributes, will be defaulted if initialized empty,
And wallet_settings.customize_wallet:
* any change of network, policy, script_type, account will unset current derivation, so that it gets re-defaulted
* if changing derivation (currently only for Miniscript) then it won't get re-defaulted.

Reset derivation (even if it was set custom for Miniscript)

---

src/krux/pages/__init__.py
src/krux/pages/mnemonic_editor.py
src/krux/pages/tiny_seed.py
src/krux/touch.py
tests/pages/test_mnemonic_editor.py

- Error appears when load Tiny seed using buttons on Amigo and then on mnemonic editor use touch to click on a word

Fix load tiny seed with button only then use touch on mnemonic editor

---

CHANGELOG.md
src/boot.py
src/krux/pages/login.py
src/krux/pages/settings_page.py
tests/pages/test_settings_page.py

The Hide Mnemonic settings will hide any BIP39 mnemonics, even newly created ones. So there is no point in enabling the New Mnemonic menu because the user will not see the mnemonic if hide is enabled.

Hide menu New Mnemonic when hide_mnemonic enabled

---

tests/pages/new_mnemonic/test_dice_rolls.py

This commit aim to target 100% on dice_rolls.py page by adding two tests, with same situation, in two different devices:
* The user begin the creation of an entropy in m5stickv but, in middle time, stop the procedure (when krux ask "proceed" and the user choose "No");
* The user begin the creation of an entropy in Amigo, but in middle time, stop the procedure (when krux ask "proceed" and the user choose "No).

Coverage 100% of src/krux/pages/new_mnemonic/dice_rolls.py

---

src/krux/bbqr.py

Fix #547 
This commit remove the checking of remaining bytes in Rfc4648 implementation of krux/src/bbqr.py::base32_decode_stream function.
* The implementation appear to be well coded and as the condition seems to be logically unreachable;
* the base_decode_stream passed by some diff fuzz tests and appear to not have any issues, attesting to the correctness of the implementation.

Removed deadcode verification

---

tests/test_bip39.py

The test_bip39.py was ignoring the case where the k_mnemonic_bytes could be called with ignore_checksum = True.
This commit just add this situation.
It's worth to mention that i tested with many bip39 vectors with [krux-fuzz](https://github.com/qlrd/krux-fuzz/blob/main/fuzz/fuzz_targets/diff_bip39.rs)

Cover 100% of test_bip39.py

---

tests/test_light.py

Fix #553
Previsouly, the `tests/test_light.py` was patching the is_on method and the real method is never executed, and thus the test pass but not hit the tested code.
This is classic situation where what we want to mock isnt the thing, but the dependencies of the thing (in this case, what is beign called inside what we want to test).
Instead mock the is_on method, is necessary to mock the `IOCircuit::circuit.value()` call (that is really what we want to test).
This commit changes the toggles in mocker from `ligth.is_on` to `light.circuit.value`.

Fix false positive call on mocking is_on method

---

CHANGELOG.md
src/krux/pages/home_pages/home.py
src/krux/pages/login.py
src/krux/pages/wallet_settings.py
tests/pages/test_wallet_settings.py

- Now when Loading a wallet or changing a loaded wallet passphrase it will preview the wallet's fingerprint for confirmation.

Added fingerprint preview when changing wallet passphrase

---

src/krux/pages/home_pages/addresses.py
tests/pages/home_pages/test_addresses.py
tests/pages/home_pages/test_home.py

Close #555
To test some miniscript cases in list_address_type,  was added:
* A main miniscript key;
* a heir miniscript key;
* a minsicript descriptor made for main/heir and where the heir can
spend after 144 blocks.
* a miniscript descriptor made for expanding multisig;
* a miniscript descriptor 3 joint custody by @Rob1Ham.
Also, was added tests cases for list_address_type for receiving and change
addresses:
* 12 word mnemonic without loading descriptor;
* 12 word mnemonic loading descriptor;
* 12 word mnemonic on a multisig without loading descriptor;
* 12 word mnemonic on a multisig loading descriptor.
* 12 word mnemonic on a miniscript (@Wizardsardine's single-inheritance) without loading
descriptor;
* 12 word mnemonic on a miniscript (@Wizardsardine's single-inheritance) loading a …

Covered multisig and miniscript cases for list_address_type

---

simulator/simulator.py

I tend to move windows around while scanning qr's and if any window glides over the simulator I lose whatever was on it until I can find something to click on.  An event WINDOWEXPOSE happens whenever an external window causes a problem but this pr is not checking for that, rather, whenever the simulator window gains focus, by keyboard,  minimize/restore or even the mouse entering the app real-estate, the screen will be redrawn w/o using update_screen().

simulator redraws screen when app regains focus

---

src/krux/printers/__init__.py
tests/printers/test_printer.py

* lint: removed unused `t` function, removed line with import commented
and sorted the imports by aphabetical order;
* tests: added test cases for create_printer function (none, thermal/adafruit,
cnc/file and cnc/grbl).

Covered 100% src/krux/printers/__init__.py

---

tests/test_sd_card.py

* added two fixtures to mock `os.stat`, so it can prepare the static method `SDHandler.dir_exists` to return  `True` or `False`;
* added two tests to cover the S`DHandler.dir_exists` cases (`True` or `False`).

Coeverage 100% src/krux/sdcard.py

---

src/krux/pages/mnemonic_editor.py

Fix #568
The `alt_wordlist` parameter in `MnemonicEditor` methods such as `compute_search_ranges()`, `autocomplete()` , and `possible_letters()`  is only meaningfully used in one specific case: when editing the final word of a new mnemonic.
In all other interactive flows (`edit()` , `edit_word()`), it is ignored, making calls such `if letter not in self.search_ranges` in line 90 and 113 effectively dead — unless forcefully tested with patched inputs.
The virtual keyboard only presents valid next letters (from `possible_letters()`), which ensures users cannot enter a letter outside the search_ranges. This makes the above line nearly impossible to hit during interactive usage — only patching tests with manual overrides can trigger it.
This commit remove the calls on these checks.

Remove deadcode in src/pages/menomic_editor.py

---

tests/test_settings.py

* The `__get__` method of `Setting` class wasn't being covered when the parameter `obj` is `None`;
* added a test case to cover the above mentioned situation: created a simple instance of `Setting` class and call its `__get__` method with a parameter `None`, expecting that the return value is the instance itself.

Cover 100% src/krux/settings.py

---

CHANGELOG.md
simulator/kruxsim/mocks/machine.py
src/krux/pages/__init__.py
src/krux/pages/home_pages/mnemonic_backup.py
src/krux/pages/tools.py
src/krux/pages/utils.py
src/krux/wallet.py
tests/pages/home_pages/test_mnemonic_backup.py
tests/pages/test_tools.py

- User prompted before printing test QR code.
- Small code optimizations/fixes regarding `qr_format` initialization (Ex: `Utils.print_standard_qr("Some data")` would raise an exception because qr_format was initialized with `None`).

Tools > Print Test QR asks before printing..

---

simulator/kruxsim/mocks/lcd.py
src/krux/display.py
src/krux/pages/__init__.py
src/krux/pages/login.py
src/krux/pages/qr_view.py
tests/conftest.py
tests/pages/test_flash_tools.py
tests/pages/test_login.py
tests/pages/test_page.py
tests/pages/test_qr_view.py
tests/shared_mocks.py
tests/test_display.py

- About screen shows an QR code alongside some text, but cube was showing only the QR code.
- Now it is possible to print QR codes smaller than screen width - needs this MaixPy PR ->  https://github.com/selfcustody/MaixPy/pull/30

Fix about screen QR code for cube

---

src/krux/power.py
tests/test_power.py

Cover `has_battery` in `src/krux/power.py` when device has no battery

Cover `has_battery` in `src/krux/power.py` when device has no battery

---

src/krux/pages/keypads.py

Fix the issue where touches on the rightmost column of the keypad did not register on the WonderMV device.

Expand keypad touch area

---

src/krux/pages/encryption_ui.py

baseconv.detect_encodings() only "hints" of a list of encodings that should be tried.
Therefore encryption_ui() must actually try/except these not-yet-validated encoding hints.
Previous to this pr, a failed decoding was raising an exception and other encoding hints were not tried.

try/except decodings in decrypt_kef

---

src/krux/pages/stack_1248.py

* `self.ctx.display.width()` will return a value equals to `NARROW_SCREEN_WITH` and never hits the line `self.x_offset = 5`;
* replacing `<` to `<=` allow to hit the line and adjust the screen on M5stickV.
Just for comparison, some photos from simulator:
**Without the change**
**With the change**

bug: fix M5stickV display size verification on `export_1248`

---

src/krux/pages/device_tests.py
tests/pages/test_device_tests.py

Followup of #618
* added warning message about possible tampering when a test fail;
* adjusted to allow pass interactive argument.
* cover situations where `deflate_compression` and
`deflate_decompression` could fail (injection of malicious code);
* added tests for possible injecion of expected codes;
* added cover case for interactive=True.

Coverage followup for device_tests

---

tests/printers/test_thermal.py

Add coverage for thermal printer qr_data_width and print_bitmap_line methods

Add coverage for `thermal.py` test  

---

tests/pages/test_file_operations.py

Tests all file save edge cases including decline save, cancel filename entry, empty/dots filename validation, and overwrite decline scenarios. Achieves 100% coverage for file_operations.py

Cover `file_operations.py` test

---

CHANGELOG.md
src/krux/pages/encryption_ui.py
src/krux/pages/login.py
src/krux/pages/wallet_settings.py

Displays passphrase an key length upon entry as a clear indicator to reduce user mistakes.

Displays passphrase and key length

---

src/krux/pages/home_pages/home.py
tests/pages/home_pages/test_home.py

Inspired on https://github.com/selfcustody/krux/pull/656, with some fixes, this commit cover the `src/krux/pages/home_pages/home.py`. Also remove an unecessary check in `src/krux/pages/home_pages/home.py::sign` method, since it alway will require a `< Back` button to return to the home page.

test: cover `src/krux/pages/home_pages/home`

---

src/krux/wallet.py
tests/test_wallet.py

- Add P2SH, P2SH_P2WSH to wallet data keys using INI format
(like in bluewallet) and removes the assumption of a native segwit at
the end of the method because it's potentially unreachable with
bluewallet UI flow -- this line only could be reachable if using a
multisig 1-of-1 described in a INI file.
- cover some cases like exporting `wallet_qr` to BBQR format.

feat+fix: add legacy and nested-segwit types to parse_key_value_file 

---

src/krux/pages/login.py

This pr removes unintentionally-left-behind pylint error/warning disablers at the top of src/krux/pages/login.py
This was an oversight that I left behind from early kef integration -- and was a pattern I used extensively, just to make progress early on.  I have done a search of similar for the entire codebase; short pylint-disablers are exceptional rather than the rule.

removes a long list of "# pylint disable:" errors and warnings

---

krux

The "Yahboom K210 Developer Kit" has been built with the '--unsuported' flag since late 2024, and was flashed like maixpy_yahboom previously.
Since unsupported boards will not be included in releases, this pr inserts support for the maixpy_yahboom_devkit in a way that chronologically preserves how old or how new this board is (after wonder_mv support, before tzt support).  Can now simply `./krux build maixpy_yahboom_devkit` (and `./krux boot maixpy_yahboom_devkit` breaking out of terminal to try it out), then `./krux flash maixpy_yahboom_devkit` to flash the board if all seems well.
The `--unsupported` flag and logic was NOT removed.

maixpy_yahboom_devkit support via krux script

---

src/krux/camera.py
tests/conftest.py
tests/pages/test_flash_tools.py
tests/shared_mocks.py
tests/test_camera.py
tests/test_power.py

Add `OV5642_ID` type in `src/krux/camera.py` as well cover tests using `bit` board in `tests/test_camera.py`.

test: add bit board and OV5642_ID type to `tests/test_camera.py`

---

CHANGELOG.md
src/krux/context.py
src/krux/input.py
src/krux/pages/__init__.py
src/krux/pages/datum_tool.py
src/krux/pages/keypads.py
src/krux/pages/mnemonic_editor.py
src/krux/pages/qr_capture.py
src/krux/pages/qr_view.py
src/krux/pages/stack_1248.py
src/krux/pages/tiny_seed.py
tests/pages/__init__.py
tests/pages/test_datum_tool.py
tests/pages/test_menu.py
tests/pages/test_mnemonic_editor.py
tests/pages/test_qr_capture.py
tests/pages/test_qr_view.py
tests/pages/test_settings_page.py
tests/pages/test_stackbit.py
tests/pages/test_tiny_seed.py
tests/test_input.py

- Refactor Turbo Buttons: consolidated FAST FORWARD / BACK logic to improve code reuse.
- Swipe Handling: Enabled SWIPE UP / DOWN on keypads, menus, and QR transcribe. Users tend to swipe vertically more due to apps like Instagram, TikTok, and browser navigation.
- Simplified Input page_event and page_prev_event
- Fix Yahboom ver 1.1 btn behavior in menus and turbo mode, improving datum-show paging.
- Type Hints: Added type hints for IDE autocomplete and static analysis without breaking MicroPython compilation (try typing `self.ctx.display.` and see the magic :star_struck: )

Refactor btn turbo and other small changes

---

src/krux/pages/login.py

Remove unused `Login._encrypted_qr_code` from `src/krux/pages/login.py`.

chore: remove unused `Login._encrypted_qr_code` from `src/krux/pages/login.py`
