MaixPy/components/micropython/core/py/mpconfig.h
krux
src/baseconv.py
src/boot.py
src/context.py
src/home.py
src/logging/LICENSE
src/logging/__init__.py
src/logging/handlers.py
src/login.py
src/menu.py
src/multisig.py
src/page.py
src/wallet.py

Resolves #9
See https://github.com/jreesun/krux/commit/ab31038dde09fc13efbb6eac1972706316427198 for details

Add support for Sparrow + Electrum, bitstring mnemonics, various fixes

---

src/home.py

Display and print QR of found receive address (#42)

---

i18n/translations/de-DE.json
i18n/translations/en-US.json
i18n/translations/es-MX.json
i18n/translations/fr-FR.json
src/home.py

Change Check Address to Scan Address (#56)

---

.gitmodules
krux
mkdocs/getting-started/installing.md

After this is merged, you'll want to run the following inside the `krux` folder:
```bash
git pull origin main && git submodule update --recursive
```

Add vendor dir and move submodules into it

---

README.md
src/boot.py

New splash

---

.pylintrc
src/krux/pages/__init__.py
src/krux/pages/login.py
tests/pages/test_login.py

@odudex I cherry-picked your commit from #92, then added my own commit with some tweaks and a new data structure to speed up the word search.
This really sped up the text input method, great idea!

Smart typing and word search speed-up

---

README.md
poetry.lock
pyproject.toml

Add dev instructions to README, update dependencies

---

src/krux/krux_settings.py
src/krux/pages/home.py
tests/pages/test_home.py

Use const to promote code re-use

Const for "thermal/adafruit"

---

CHANGELOG.md

Small text changes on CHANGELOG.md

---

docs/faq.en.md

new FAQ item about firmware issues

Docs new FAQ item about firmware issues

---

docs/faq.en.md
docs/getting-started/features/QR-transcript-tools.en.md
docs/getting-started/features/sd-card-update.en.md
docs/getting-started/usage/loading-a-mnemonic.en.md
docs/getting-started/usage/navigating-the-main-menu.en.md
docs/parts.en.md
docs/snippets/12th-24th-word-generate.md
docs/snippets/m5stickv-usb-c.md

Info about templates and additional info about printing mnemonic

docs adding info about templates

---

docs/parts.en.md

Updating info where to find device distributors

Updating info where to find device distributors

---

tests/test_firmware.py

* added 2 tests to check firmware constants.
* altered untested configuraton variables to point at new slot-2, just for the sake of consistency.

added tests to check firmware constants

---

docs/index.en.md
docs/parts.en.md

* Added dock and yahboom to index
* Changed device imgs to match size in index and parts

Docs update

---

src/krux/key.py
src/krux/pages/wallet_settings.py

Adds multisig "account" support to wallet_customization branch.

Multisig "Account"s for wallet_customization

---

src/krux/psbt.py

If it's good for single-sig, why not for multisig too?
* checks all inputs (instead of first only)
* checks for all xpubs (which seems fine for sparrow but must test other coordinators),
* might return more than a single path, comma separated
* tested for up to 21 inputs (but many inputs and multisigs of high "n" might get out of hand)
As of Friday April 12th, testing has succeeded for up to 400 path-mismatch checks on sparrow, specter-desktop and nunchuk.  (via a 6input to 1output 9of16 multisig psbt of size 17724 base64 chars).

path_mismatch refactor for every input, every pubkey, including multisig

---

docs/getting-started/features/QR-transcript-tools.en.md
docs/getting-started/features/tools.en.md
docs/getting-started/usage/loading-a-mnemonic.en.md

Swipe left or right info to help with input

Adding info about swipe to help input passphrase

---

src/krux/key.py
src/krux/krux_settings.py
src/krux/pages/__init__.py
src/krux/pages/settings_page.py
src/krux/pages/wallet_settings.py
src/krux/settings.py

- Write "Test" to top bar instead of "test"
- Code reuse of str "test" and "main"

Code reuse for "test" and "main" str

---

README.md

proposal of solution for poetry installation

---

src/krux/key.py
src/krux/pages/home_pages/pub_key_view.py
src/krux/pages/login.py
src/krux/pages/wallet_settings.py
src/krux/psbt.py
src/krux/wallet.py

Created variables `P2PKH, P2SH, P2SH_P2WPKH, P2SH_P2WSH, P2WPKH, P2WSH, P2TR` to reuse and help developers understand what it means with helper comments

Refactor to reuse variables for script types

---

docs/getting-started/features/tools.en.md
docs/parts.en.md
src/krux/format.py
src/krux/pages/file_manager.py
src/krux/pages/tools.py

- Refactor for reuse of variables and code (DRY principle)

Code refactor and reuse

---

docs/getting-started/installing/from-pre-built-release.en.md
docs/getting-started/installing/from-source.en.md
docs/getting-started/installing/from-test-release.en.md

DOCS: Added info about installing from command line using a Mac

Docs added Mac command line instructions

---

README.md
simulator/generate-device-screenshots.sh

* Uses `poetry run poe simulator` instead of `poetry run python simulator.py` for screenshots.
* README.md mentions removal of compiler at top of "Live debug a device" section, instead of at bottom.

Assorted non-firmware changes for release-24.07.0

---

docs/getting-started/navigation.en.md

Updated mind maps to better reflect the actual navigation (v24.07.0)

Updated mind maps to better reflect the actual navigation (v24.07.0)

---

src/krux/pages/login.py
tests/pages/test_login.py

Now about shows hardware alongside version

About shows board hardware

---

README.md

complemented instructions on README

README info about add user to docker group before using ./krux build

---

src/krux/settings.py
tests/test_settings.py

When user had an old settings file in the SD (like when updating from an old version), change in settings would not show up when the device restarts (appeared as not persisted)
Below attached a settings file to help testing with your SD card:
[settings.json](https://github.com/user-attachments/files/17942197/settings.json)

Fix incorrect settings in SD changing user defined values in flash

---

src/krux/pages/login.py
tests/pages/test_login.py

Add the project site to about section

Add site selfcustody.github.io/krux to about

---

simulator/kruxsim/mocks/lcd.py

Adds missing support for ja-JP fonts in simulator

resolves simulator support for ja-JP

---

docs/getting-started/features/tamper-detection.en.md
docs/getting-started/installing/from-gui/debian-like.en.md
docs/getting-started/installing/from-gui/fedora-like.en.md
docs/getting-started/installing/from-gui/index.en.md
docs/getting-started/installing/from-gui/macos-arm64.en.md
docs/getting-started/installing/from-gui/macos-intel.en.md
docs/getting-started/installing/from-gui/other-linux-distro.en.md
docs/getting-started/installing/from-gui/usage.en.md
docs/getting-started/installing/from-gui/windows.en.md
docs/getting-started/installing/from-pre-built-release.en.md
docs/getting-started/installing/index.en.md
docs/snippets/after-install-installer.en.txt
docs/snippets/install-installer-macos.en.txt
docs/troubleshooting.en.md

DOCS:
- Fixed Krux-Installer text
- Fixed missing snippet file
- Fixed `wondermv` install instructions

Docs: Krux-Installer txts and missing snippet after install

---

README.md

Fix device imgs README.md

---

src/krux/pages/tiny_seed.py

Fix and eventual error being raised while scanning 24 words binary grids.
Thanks @tadeubas for catching!

binary grid scan 24w validation fix

---

.github/PULL_REQUEST_TEMPLATE.md

Github template update

---

CHANGELOG.md
simulator/kruxsim/mocks/machine.py
simulator/kruxsim/mocks/sensor.py
src/krux/context.py
src/krux/krux_settings.py
src/krux/pages/home_pages/mnemonic_backup.py
src/krux/pages/print_page.py
tests/pages/__init__.py
tests/pages/home_pages/test_mnemonic_backup.py
tests/test_context.py

- Fix printing words instead of numbers when using "Backup Mnemonic > Other formats > Numbers".
- Small code cleanup

Fix print for bkp numbers

---

docs/getting-started/installing/from-gui/usage.en.md
docs/troubleshooting.en.md

Docs Troubleshooting more info about screen stuck on logo

Docs troubleshooting added info

---

README.md

Add info about Krux-Installer to README, helping users to find it.

Add info about Krux-Installer to README

---

docs/css/custom.css
docs/getting-started/index.en.md
docs/parts.en.md

Add info on docs about Electrum Wallet incompatibility.

Docs add Liana and Electrum warn incompatible

---

tests/test_input.py

* cover the `__handler__` function;
* mocked pins to cover it.

Cover 100% src/krux/rotary.py

---

src/krux/printers/cnc.py

Fix https://github.com/selfcustody/krux/pull/562 that broke build process due to invalid syntax on `cnc.py`

Fix broken build process due to invalid syntax

---

.github/PULL_REQUEST_TEMPLATE.md

Update pull request template to remember to test on device

Update github PR template

---

pyproject.toml
src/krux/psbt.py

Code reuse for PSBTSigner outputs

PSBTSigner output msg code reuse and small changes

---

.github/PULL_REQUEST_TEMPLATE.md

Fix #578
While this is very important to ask if the developer built the firmware on a device, it lacks more information about the build. Providing the device's name could add more context about the PR.

Followup of PR 557

---

tests/test_firmware.py

100% coverage on firmware tests

Firmware tests 100% cov

---

tests/pages/test_print_page.py

* add test for a not defined print driver;
* add test for a cnc/file print driver.

Coverage 100% src/krux/pages/print_page.py

---

docs/css/custom.css
docs/getting-started/index.en.md
docs/getting-started/usage/setting-a-coordinator-and-signing.en.md
docs/getting-started/usage/video-tutorials.en.md
mkdocs.yml

- Added Bitcoin Safe coordinator
- Added 2 EN videos
- Reworked videos page

Docs add Bitcoin Safe and more english videos

---

tests/test_buttons.py

* add test for __handler__ method;
* add test for generic button initialization;
* add test for release button events.

Coverage 100% src/krux/buttons.py

---

simulator/kruxsim/mocks/baseconv.py
simulator/simulator.py
src/krux/bbqr.py
src/krux/psbt.py
tests/conftest.py
tests/shared_mocks.py
tests/test_bbqr.py
tests/test_qr.py

Switch to C code based base32 encoding and decoding

---

tests/touchscreens/test_ft6x36.py

* added a mock fixture to `tests/test_ft6x36.py`;
* added a handler test

Cover 100% `src/krux/touchscreens/ft6x36.py`

---

CHANGELOG.md
src/krux/pages/keypads.py
src/krux/touch.py

- Expand keypad touch area to the left side.
- Fix keypad index logics for the case where left edge pixel is clicked

Touch adjusts

---

tests/pages/test_fill_flash.py

Test amigo device flash with camera entropy data simulating user interaction flows

Improve coverage `/tests/pages/test_fill_flash.py`

---

src/krux/pages/home_pages/bip85.py
tests/pages/home_pages/test_bip85.py
tests/pages/home_pages/test_home.py

More intuitive menu navigation, where "< Back" or "Esc" return to previous menu, instead of leaving BIP85.

BIP85 - More Intuitive Navigation

---

firmware/font/missing_glyphs.py

Adds `missing_glyphs.py` tool to ./firmware/font/ for:
* finding missing glyphs per project,
* for creating a file of all needed characters, like `allchars.txt` -- for inspection on device in Datum Tool.

./firmware/font/missing_glyphs.py script

---

firmware/font/bdftokff.py
pyproject.toml

Avoid unnecessary errors by treating all MaixPy projects not listed in the script as using font size 16

bdftokff: apply font 16 to projects not listed

---

docs/getting-started/navigation.en.md

Update Gitmind Navigation overview maps

Update docs navigation
